src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecetteRepository::class)
 */
class Recette
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=IngredientsRecette::class, mappedBy="recette_id")
     */
    private $ingredientsRecette_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity=Etapes::class, mappedBy="recette_id")
     */
    private $etapes_id;

    /**
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="recette_id")
     */
    private $commentaires_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $temps_preparation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $temps_cuisson;

    /**
     * @ORM\OneToMany(targetEntity=Notes::class, mappedBy="recette_id")
     */
    private $notes_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_personnes;

    /**
     * @ORM\Column(type="integer")
     */
    private $difficulte;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="recettes_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author_id;

    /**
     * @ORM\ManyToOne(targetEntity=Cuisson::class, inversedBy="recettes_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cuisson_id;

    /**
     * @ORM\ManyToOne(targetEntity=Alimentation::class, inversedBy="recettes_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $alimentation_id;

    /**
     * @ORM\ManyToOne(targetEntity=Plats::class, inversedBy="recettes_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $plats_id;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="recettes_fav_id")
     */
    private $users_fav_id;

    public function __construct()
    {
        $this->ingredientsRecette_id = new ArrayCollection();
        $this->etapes_id = new ArrayCollection();
        $this->commentaires_id = new ArrayCollection();
        $this->notes_id = new ArrayCollection();
        $this->users_fav_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|IngredientsRecette[]
     */
    public function getIngredientsRecetteId(): Collection
    {
        return $this->ingredientsRecette_id;
    }

    public function addIngredientsRecetteId(IngredientsRecette $ingredientsRecetteId): self
    {
        if (!$this->ingredientsRecette_id->contains($ingredientsRecetteId)) {
            $this->ingredientsRecette_id[] = $ingredientsRecetteId;
            $ingredientsRecetteId->setRecetteId($this);
        }

        return $this;
    }

    public function removeIngredientsRecetteId(IngredientsRecette $ingredientsRecetteId): self
    {
        if ($this->ingredientsRecette_id->removeElement($ingredientsRecetteId)) {
            // set the owning side to null (unless already changed)
            if ($ingredientsRecetteId->getRecetteId() === $this) {
                $ingredientsRecetteId->setRecetteId(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|etapes[]
     */
    public function getEtapesId(): Collection
    {
        return $this->etapes_id;
    }

    public function addEtapesId(etapes $etapesId): self
    {
        if (!$this->etapes_id->contains($etapesId)) {
            $this->etapes_id[] = $etapesId;
            $etapesId->setRecetteId($this);
        }

        return $this;
    }

    public function removeEtapesId(etapes $etapesId): self
    {
        if ($this->etapes_id->removeElement($etapesId)) {
            // set the owning side to null (unless already changed)
            if ($etapesId->getRecetteId() === $this) {
                $etapesId->setRecetteId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentairesId(): Collection
    {
        return $this->commentaires_id;
    }

    public function addCommentairesId(Commentaires $commentairesId): self
    {
        if (!$this->commentaires_id->contains($commentairesId)) {
            $this->commentaires_id[] = $commentairesId;
            $commentairesId->setRecetteId($this);
        }

        return $this;
    }

    public function removeCommentairesId(Commentaires $commentairesId): self
    {
        if ($this->commentaires_id->removeElement($commentairesId)) {
            // set the owning side to null (unless already changed)
            if ($commentairesId->getRecetteId() === $this) {
                $commentairesId->setRecetteId(null);
            }
        }

        return $this;
    }

    public function getTempsPreparation(): ?int
    {
        return $this->temps_preparation;
    }

    public function setTempsPreparation(?int $temps_preparation): self
    {
        $this->temps_preparation = $temps_preparation;

        return $this;
    }

    public function getTempsCuisson(): ?int
    {
        return $this->temps_cuisson;
    }

    public function setTempsCuisson(?int $temps_cuisson): self
    {
        $this->temps_cuisson = $temps_cuisson;

        return $this;
    }

    /**
     * @return Collection|Notes[]
     */
    public function getNotesId(): Collection
    {
        return $this->notes_id;
    }

    public function addNotesId(Notes $notesId): self
    {
        if (!$this->notes_id->contains($notesId)) {
            $this->notes_id[] = $notesId;
            $notesId->setRecetteId($this);
        }

        return $this;
    }

    public function removeNotesId(Notes $notesId): self
    {
        if ($this->notes_id->removeElement($notesId)) {
            // set the owning side to null (unless already changed)
            if ($notesId->getRecetteId() === $this) {
                $notesId->setRecetteId(null);
            }
        }

        return $this;
    }

    public function getNbPersonnes(): ?int
    {
        return $this->nb_personnes;
    }

    public function setNbPersonnes(?int $nb_personnes): self
    {
        $this->nb_personnes = $nb_personnes;

        return $this;
    }

    public function getDifficulte(): ?int
    {
        return $this->difficulte;
    }

    public function setDifficulte(int $difficulte): self
    {
        $this->difficulte = $difficulte;

        return $this;
    }

    public function getAuthorId(): ?user
    {
        return $this->author_id;
    }

    public function setAuthorId(?user $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getCuissonId(): ?cuisson
    {
        return $this->cuisson_id;
    }

    public function setCuissonId(?cuisson $cuisson_id): self
    {
        $this->cuisson_id = $cuisson_id;

        return $this;
    }

    public function getAlimentationId(): ?Alimentation
    {
        return $this->alimentation_id;
    }

    public function setAlimentationId(?Alimentation $alimentation_id): self
    {
        $this->alimentation_id = $alimentation_id;

        return $this;
    }

    public function getPlatsId(): ?Plats
    {
        return $this->plats_id;
    }

    public function setPlatsId(?Plats $plats_id): self
    {
        $this->plats_id = $plats_id;

        return $this;
    }

    /**
     * @return Collection|user[]
     */
    public function getUsersFavId(): Collection
    {
        return $this->users_fav_id;
    }

    public function addUsersFavId(user $usersFavId): self
    {
        if (!$this->users_fav_id->contains($usersFavId)) {
            $this->users_fav_id[] = $usersFavId;
        }

        return $this;
    }

    public function removeUsersFavId(user $usersFavId): self
    {
        $this->users_fav_id->removeElement($usersFavId);

        return $this;
    }

     public function __toString() {

         return "$this->id";
     }

 }

src/Controller/AdministrationRecetteController.php
<?php

namespace App\Controller;

use App\Entity\Recette;
use App\Form\RecetteType;
use App\Repository\RecetteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/administration/recette")
 */
class AdministrationRecetteController extends AbstractController
{
    /**
     * @Route("/", name="administration_recette_index", methods={"GET"})
     */
    public function index(RecetteRepository $recetteRepository): Response
    {
        return $this->render('administration_recette/index.html.twig', [
            'recettes' => $recetteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="administration_recette_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $recette = new Recette();
        $form = $this->createForm(RecetteType::class, $recette);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recette);
            $entityManager->flush();

            return $this->redirectToRoute('administration_recette_index');
        }

        return $this->render('administration_recette/new.html.twig', [
            'recette' => $recette,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="administration_recette_show", methods={"GET"})
     */
    public function show(Recette $recette): Response
    {
        return $this->render('administration_recette/show.html.twig', [
            'recette' => $recette,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="administration_recette_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Recette $recette): Response
    {
        $form = $this->createForm(RecetteType::class, $recette);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('administration_recette_index');
        }

        return $this->render('administration_recette/edit.html.twig', [
            'recette' => $recette,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="administration_recette_delete", methods={"POST"})
     */
    public function delete(Request $request, Recette $recette): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recette->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($recette);
            $entityManager->flush();
        }

        return $this->redirectToRoute('administration_recette_index');
    }
}

templates/administration_recette/_delete_form.html.twig
 {# ? Feuille du bouton Delete #ModeAdmin #}

     <form method="post" action="{{ path('administration_recette_delete', {'id': recette.id}) }}" onsubmit="return confirm('Voulez vraiment supprimer cette recette?');">
     
         <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recette.id) }}">
     
         <button class="btn col-12 btn-secondary btn-lg">
              Supprimer 
         </button>
     
     </form>

templates/administration_recette/_form.html.twig
     {{ form_start(form) }}

         <article class="flex-container3 text-center">

             <div class="row">

                 {# ********** NOM DE LA RECETTE ********** #}     

                 <section class="col-sm-4">  

                     {# *** LABEL *** #}
                     <legend> Nom de la recette </legend>
                 
                     {# *** INPUT *** #}
                     {{ form_widget(form.name,{ 
                 
                         'attr': { 
                 
                         'class':'name',
                         'placeholder':'Entrer un nom de recette'
                         
                         }}) }}  
                 
                 </section>

                 {# ********** Niveau de difficulté ********** #}     

                 <section class="col-sm-4">  

                     {# *** LABEL *** #}
                     <legend> Niveau de difficulté </legend>
                   
                     {# *** INPUT *** #}
                     {{ form_widget(form.difficulte,{ 
                   
                         'attr': {                        
                             'class':'difficulte',
                             'placeholder':'Entrez un niveau de 1 à 3'       
                         }

                     }) }} 
                 
                 </section>

                 {# ********** Temps de préparation ********** #} 

                 <section class="col-sm-4">  

                     {# *** LABEL *** #}
                     <legend> Temps de préparation </legend>
                    
                     {# *** INPUT *** #}
                     {{ form_widget(form.temps_preparation,{ 
                    
                         'attr': {                        
                             'class':'temps_preparation',
                             'placeholder':'Entrez un temps de préparation'       
                         }

                     }) }} 
                 
                 </section>

             </div>  

             <div class="row">      

                 {# ********** Temps de cuisson ********** #} 
   
                 <section class="col-sm-4">  

                     {# *** LABEL *** #}
                     <legend> Temps de cuisson </legend>
                      
                     {# *** INPUT *** #}
                     {{ form_widget(form.temps_cuisson,{ 
                
                         'attr': {                        
                             'class':'temps_cuisson',
                             'placeholder':'Entrez un temps de cuisson'       
                         }

                     }) }} 

                 </section>

                 {# ********** Nombre de personnes ********** #} 
   
                 <section class="col-sm-4"> 

                     {# *** LABEL *** #}
                     <legend> Nombre de personnes </legend>
                 
                     {# *** INPUT *** #}
                     {{ form_widget(form.nb_personnes,{ 
                    
                         'attr': {                        
                             'class':'nb_personnes',
                             'placeholder':'Entrez un nombre de personnes'       
                         }

                     }) }} 

                 </section>

                  {# ********** Type d'alimentation ********** #} 

                 <section class="col-sm-4"> 

                     {# *** LABEL *** #}
                     <legend> Type d'alimentation </legend>
                   
                     {# *** INPUT *** #}
                     {{ form_widget(form.alimentation_id,{ 
                   
                         'attr': {                        
                             'class':'alimentation_id',
                             'placeholder':'Entrez un type d_alimentation'       
                         }

                     }) }} 

                 </section>  

             </div> 

             <div class="row">       

                 {# ********** Type de plat ********** #} 

                 <section class="col-sm-4"> 

                     {# *** LABEL *** #}
                     <legend> Type de plat </legend>
                   
                     {# *** INPUT *** #}
                     {{ form_widget(form.plats_id,{ 
                   
                         'attr': {                        
                             'class':'plats_id',
                             'placeholder':'Entrez un type de plat'       
                         }

                     }) }} 

                 </section>

                 {# ********** Type de cuisson ********** #} 

                 <section class="col-sm-4"> 

                     {# *** LABEL *** #}
                     <legend> Type de cuisson </legend>
                 
                     {# *** INPUT *** #}
                     {{ form_widget(form.cuisson_id,{ 
                   
                         'attr': {                        
                             'class':'cuisson_id',
                             'placeholder':'Entrez un type de cuisson'       
                         }

                     }) }} 

                 </section>
                 
                 {# ********** Image de la recette ********** #} 

                 <section class="col-sm-4"> 

                     {# *** LABEL *** #}
                     <legend> Image </legend>
                 
                     {# *** INPUT *** #}
                     {{ form_widget(form.image,{ 
                    
                         'attr': {                        
                             'class':'image',
                             'placeholder':''       
                         }

                     }) }} 

                 </section> 
             
             </div>  

             <hr/>

          </article> 
        
         <button class="btn col-12 btn-dark btn-lg px-4 gap-3"> 
             {{ button_label|default('Sauvegarder') }} 
         </button>
     
     {{ form_end(form) }}

templates/administration_recette/edit.html.twig
 {# ? Feuille : Modifier une recette #ModeAdmin #} 
 
 {% extends 'base.html.twig' %}
 
     {% block metaTitle %}
         " Modifier une recette "
     {% endblock %}

     {% block title %}
         Modifier une recette
     {% endblock %}
     
     {% block body %}
  
         <main class="Form"> 

             <div class="py-5 text-center col-12">

                {# *********************************************** #}

                 <section>
   
                     <h1> Modifier une recette </h1>

                         <hr/>

                             <p> 
                                 <em> Consulter la liste des recette de votre site et les administrer. </em>  📇 
                             </p>

                         <hr/>

                 </section>  
 
                 {# *********************************************** #}

                 <article class="col-12">
                    
                     {{ include('administration_recette/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
                 
                     <a href="{{ path('administration_recette_index') }}" type="submit" class="btn btn-success col-12 btn-lg">                                
                         Retour à la liste
                     </a>

                     <hr/>
                   
                     {{ include('administration_recette/_delete_form.html.twig') }}

                     {# ! todo: Le bouton " Supprimer " ne fonctionne pas #}

                 </article> 

                 {# *********************************************** #}

             </div> 

         </main>

     {% endblock %}

templates/administration_recette/index.html.twig
 {# ? Feuille : Gestion des recettes #ModeAdmin #} 

 {% extends 'base.html.twig' %}
 
     {% block metaTitle %}
         " Gestion des recettes "
     {% endblock %}

     {% block title %}
         Gestion des recettes
     {% endblock %}
     
     {% block body %}

         <main class="Form">  

             <div class="text-center">

                 {# *********************************************** #}

                 <section>
    
                     <h1> Gestion des recettes </h1>
         
                         <hr/>

                             <p> 
                                 <em> Consulter la liste des recettes de votre site et les administrés. </em>  📓
                             </p>

                         <hr/>

                 </section>

                 {# ? Partie: Barre de recherche User #}

                 <h6> <kbd> Barre de recherche par filtre en cours d'intégration: Work In Progress ⚠️ </kbd> </h6>
                 <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Entrer un mot clé pour effectuer une recherche rapide...">

                     <article>
     
                         <table id="myTable" class="table table-dark table-hover">

                             <thead>

                             {# ! todo: La fonction " Barre de recherche ne fonctionne pas encore. #}
                             {# ! Je voudrais intégrer une barre de recherche > qui appplique un filtre sur nos champs #}
                             {# !  Table filtre > Source: https://www.w3schools.com/howto/howto_js_filter_table.asp #}

                             <script>

                                 function myFunction() {

                                     // Declare variables
                                     var input, filter, table, tr, th, i, txtValue;
                                     input = document.getElementById("myInput");
                                     filter = input.value.toUpperCase();
                                     table = document.getElementById("myTable");
                                     tr = table.getElementsByTagName("tr");
                                 
                                     // Loop through all table rows, and hide those who don't match the search query
                                     for (i = 0; i < tr.length; i++) {

                                         th = tr[i].getElementsByTagName("th")[0];

                                         if (th) {

                                             txtValue = th.textContent || th.innerText;

                                             if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                                 tr[i].style.display = "";
                                             } 
                                             
                                             else {
                                                 tr[i].style.display = "none";
                                             }

                                         }

                                     }


                                 }

                             </script>    

                                 <tr class="header">
                                     <th> Id </th>
                                     <th> Nom </th>
                                     <th> Image </th>
                                     <th> Temps de préparation </th>
                                     <th> Temps de cuisson </th>
                                     <th> Nombre de personnes </th>
                                     <th> Difficulté </th>
                                     <th> Actions </th>
                                 </tr>

                             </thead>

                             <tbody>

                                 {% for recette in recettes %}
                                 
                                     <tr>
                                         <td> {{ recette.id }} </td>
                                         <td> {{ recette.name }} </td>
                                         <td> {{ recette.image ? 'oui' : 'non' }}  </td>
                                         <td> {{ recette.tempsPreparation }} </td>
                                         <td> {{ recette.tempsCuisson }} </td>
                                         <td> {{ recette.nbPersonnes }} </td>
                                         <td> {{ recette.difficulte }} </td>

                                         <td>

                                             <section class="btn-group">
                                             
                                                 <a href="{{ path('administration_recette_show', {'id': recette.id}) }}" type="submit" class="btn btn-success btn-lg col-12">
                                                     Voir
                                                 </a>

                                                 <a href="{{ path('administration_recette_edit', {'id': recette.id}) }}" type="submit" class="btn btn-success btn-lg col-12"> 
                                                     Modifier 
                                                 </a>
                                      
                                             </td>

                                         </td>

                                     </tr>

                                 {% else %}

                                     <tr>
                                         <td colspan="8"> Aucun élément ne correspond à votre recherche </td>
                                     </tr>

                                 {% endfor %}

                             </tbody>

                         </table>
     
                         {# *********************************************** #}

                         <hr/>

                         <section class="btn-group-vertical col-12 ">

                             <a href="{{ path('administration_recette_new') }}" class="btn btn-dark col-12 btn-lg px-4 gap-3"> 
                                 Créer une nouvelle recette
                             </a>
 
                             <a href="{{ path('interface_administration') }}" class="btn btn-success col-12 btn-lg px-4 gap-3">
                                 Retour à l'interface d'administration
                             </a>    

                         </section>    

                         {# *********************************************** #}

                     </article>

             </div>       

         </main>  

     {% endblock %}
 

templates/administration_recette/show.html.twig
 {# ? Feuille : Gestion des recettes #ModeAdmin #} 

 {% extends 'base.html.twig' %}

     {% block metaTitle %}
         " Recette"
     {% endblock %}

     {% block title %}   
         Recette         
     {% endblock %}
     
     {% block body %}

         <main class="Form"> 
     
             <div  class="py-5 text-center col-12">
         
                 {# *********************************************** #}

                 <section>
 
                     <h1> Recette </h1>

                         <hr/>

                             <p> 
                                 <em> Informations sur la recette de l'utilisateur ! </em> 👾
                             </p>

                         <hr/>

                 </section>

                 {# *********************************************** #}
  
                 <article>

                     <table class="table table-dark table-hover">

                         <tbody>

                             <tr>
                                 <th> Id </th>
                                 <td> {{ recette.id }} </td>
                             </tr>

                             <tr>
                                 <th> Nom de la recette </th>
                                 <td> {{ recette.name }} </td>
                             </tr> 
 
                             <tr> 
                                 <th> Image </th>
                                 <td> {{ recette.image ? 'oui' : 'non' }}  </td>
                             </tr> 
 
                             <tr> 
                                 <th> Temps de préparation </th>
                                 <td> {{ recette.tempsPreparation }} </td>
                             </tr> 
 
                             <tr> 
                                 <th> Temps de cuisson </th>
                                 <td> {{ recette.tempsCuisson }} </td>
                             </tr> 
 
                             <tr> 
                                 <th> Nombre de personnes </th>
                                 <td> {{ recette.nbPersonnes }} </td>
                             </tr> 
 
                             <tr> 
                                 <th> Difficulté </th>
                                 <td> {{ recette.difficulte }} </td>
                             </tr> 

                         </tbody>

                     </table>
     
                 </article>

                 {# *********************************************** #}

                 <hr/>

                 <article class="btn-group-vertical col-12">

                     <a href="{{ path('administration_recette_edit', {'id': recette.id}) }}" class="btn btn-dark col-12 btn-lg px-4 gap-3">                                
                         Modifier
                     </a>
    
                     <a href="{{ path('administration_recette_index') }}" class="btn btn-success col-12 btn-lg px-4 gap-3">                                
                         Retour à la liste 
                     </a>

                 </article>

                 <hr/>

                 <article class="col-12">

                     {{ include('administration_recette/_delete_form.html.twig') }}

                 </article>

                 {# *********************************************** #}

             </div>      

         </main>   

     {% endblock %}